services:
  app:
    build:
      context: ./MistakeApp
      dockerfile: Dockerfile
  reverse-proxy:
    build:
      context: ./ReverseProxy
      dockerfile: Dockerfile
    ports:
      - "8000:80"
